In [20]:
import numpy as np

In [21]:
"""
Numpy
"""
# Creating on array
print(np.arange(3))
print(np.arange(3, 9))
print(np.arange(3, 9, 2))



[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [22]:
# Seed for reproducibility
#Random cimber generator
np.random.seed(0)

arr1 = np.random.randint(10, size = 6)        # 1D array
arr2 = np.random.randint(10, size = (3, 4))   # 2D array
arr3 = np.random.randint(10, size = (3, 4, 5))# 3D array
print(arr1)
print(arr2)
print(arr3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [23]:
# Arributes
print(arr2)

print("arr2.ndim = ",arr2.ndim)
print("arr2.shape = ",arr2.shape)
print("arr2.size = ",arr2.size)

print("arr2.dtype = ",arr2.dtype)
print("arr2.itemsize = ",arr2.itemsize)
print("arr2.nbytes = ",arr2.nbytes)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
arr2.ndim =  2
arr2.shape =  (3, 4)
arr2.size =  12
arr2.dtype =  int32
arr2.itemsize =  4
arr2.nbytes =  48


In [24]:
# Multi-dimensional Subarrrays
np.random.seed(0)
arr = np.random.randint(10, size=(6,8))
print(arr)

arr_sub = arr[3:5, 4:7]
print(arr_sub)

[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]]
[[5 0 2]
 [3 7 0]]


In [25]:
np.random.seed(0)
arr = np.random.randint(10, size = (7, 5))
print(arr[:2, :3])


arr = np.random.randint(10, size = (7, 5))
print(arr[:3, ::2])

[[5 0 3]
 [9 3 5]]
[[3 7 1]
 [9 0 7]
 [3 7 0]]


In [26]:
arr2 = np.array([12, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7])
print(arr)

arr2_sub = arr2[:2, :2].copy()
print(arr_sub)

arr2_sub[0, 0] = 100
print(arr_sub[0, 0])


TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [27]:
arr_1 = np,array([1,2,3])
arr_2 = np,array([4,5,6])
arr_3 = np,array([7,8,9])

arr_total = np.concatenate([arr_1, arr_2, arr_3])
print(arr_total, "\n")
arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total, "\n")

NameError: name 'array' is not defined

In [31]:
arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr)

arr_1, arr_2, arr_3 = np.split(arr, [3, 5])
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [99 99] [3 2 1]
