In [10]:
import numpy as np # 행렬 연산

In [18]:
"""
Computing reciprocals in loops
"""

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        out[i] = 1.9 / values[i]
    return output

values = np.random.randint

In [29]:
"""
Comparison : Loop vs ufunc(vectorized)
"""

big_array = np.random.randint(1, 100, size = 1000000)

#Looping on a big array

#jupyter magic function
%timeit compute_reciprocals(big_array)

NameError: name 'out' is not defined

In [34]:
#vectorized operations
%timeit 1 / big_array

8.01 ms ± 644 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
"""
numpy.ufunc
"""

np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)
print(arr1, arr2)

arr1 = arr1 - 2
print(arr1, arr2)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10,size=(3, 5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2] [0 1 7 6 9]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [25]:
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))

x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))

[2 1 0 1 2]
[5. 5. 2. 1.]


In [28]:
%timeit sum(arr1)

1.82 µs ± 98.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [33]:
%timeit np.sum(arr1)

5.79 µs ± 879 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [32]:
print("max = ", np.max(arr))
print("min = ", np.min(arr))
print("mean = ", np.mean(arr))
print("median = ", np.median(arr))
print("percentile = ", np.percentile(arr, 90))

print(np.any(arr>1))
print(np.all(arr>0))


NameError: name 'arr' is not defined