In [3]:
def create_puramid(rows):
    
    for i in range(rows):
        print('*' * (i+1))

In [6]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [16]:
# Creating a NumPy Array
lst = [1.5, "string", True]

arr = np.array(lst)
print(arr)

['1.5' 'string' 'True']


In [17]:
# .dtype attribute
print(arr.dtype)

<U32


In [18]:
"""
Sizs Comparison of ndarray and list object
"""

from sys import getsizeof

lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
print(getsizeof(lst)) # int + object meta info.

arr = np.array(lst) # int(4byte)
print(getsizeof(arr))

192
172


In [20]:
"""
Operations with NumPy Arrays
"""
prices = [30, 25, 40 , 20 , 20, 35, 50, 35]

# With a list
new_prices = [price-5 for price in prices]
print(new_prices)

# With a ndarray
prices_arr = np.array(prices)
prices_arr = prices_arr - 5
print(prices_arr)

# ** operation and np.sqrt



[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [28]:
"""
Exercise: Test Scores
"""

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)
manual_aswoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_aswoa_test_1)

student_scores = np.array([test_1, test_2, test_3])
print(student_scores)

print(student_scores[2, 0])

print(student_scores[:, 4])

[89 87 74 92 94]
[258 279 246 274 270]
[86.         93.         82.         91.33333333 90.        ]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [32]:
"""
Logical Operations with Arrays
"""
#masking
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
mask = a > 5
print(mask)

# select using logical operations
selected = a[a > 5]
print(selected)

# combined Logical operations 논리합|,  &
selected = a[(a > 6) | (a < 4)]
print(selected)

selected = a[(a > 4) & (a < 8)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[5 7]


In [ ]:
#실습 문제: 골디락스 포리지(죽)페스티벌
#페스티벌 아침에 만들어진 포리지의 온도를 바탕으로 평가
#각 포리지의 온도를 porridge배열에 저장하시오 79 65 50 
#온도가 60도 미만인 포리지들은 cold배열에 저장

#온도가 80도 초과인 포리지들은 hot배열에 저장
